### ISSUE TITLE
Hood angles

### ISSUE THREAD

**Issue by TylerSeiford** [TylerSeiford/xrc-py#3]
Eliot's hood control from https://github.com/Coolgamertag/xRc-Automation/ is a good start, but there's a good amount of bounce-outs.

Ideally, we'd record some gameplay data, extrapolate ball behavior from that, and use that data to generate a new table.

**Comment by TylerSeiford** [comment]
As an expansion, we could add shoot-while-in-motion once we have this data.

**Comment by MongooseTNM** [comment]
I found that this line of code works better than the table     TAngle = -45*Dist+215   i dont really know how you could implement it but its from eliots 973 script

**Comment by TylerSeiford** [comment]
I'm going to keep this open for further improvements on the hood angles, but after manually re-tuning them I feel like it's pretty close to ideal.

For reference, here's a comparison between the original, old, new, and eliot's 973 formula mentioned above.
![image](https://user-images.githubusercontent.com/50031864/173257247-ef76606c-9cd7-4321-852d-b1696b71bbe4.png)

As you can see, there are some discontinuities where I switch from a mostly linear trying to get the balls directly in the center of the hub (to reduce bounce outs when close) to trying to bounce the balls off of the back of the hub (to reduce bounce outs when far) to 0 to indicate being outside the range of the bot, and even 4.5/4.6 is still on the edge of the range.
